### ISSUE TITLE
problems in installing the GPU support serving-caffe

### ISSUE THREAD

**Issue by fuyiqin** [rayglover-ibm/serving-caffe#5]
when I install the GPU support serving-caffe ，I find some problems such as：
ERROR: /root/.cache/bazel/_bazel_root/d03653773418e826936cf1555ad07736/external/caffe/BUILD.bazel:54:11: in cmd attribute of genrule rule @caffe//:configure: label '@local_config_cuda//cuda:cudnn' in $(location) expression expression expands to no files.
ERROR: /root/.cache/bazel/_bazel_root/d03653773418e826936cf1555ad07736/external/caffe/BUILD.bazel:54:11: in cmd attribute of genrule rule @caffe//:configure: $(location :protobuf-root) not defined.
ERROR: Analysis of target '@caffe//:lib' failed; build aborted.

how can I solve it？

**Comment by rayglover-ibm** [comment]
To be clear, does the cpu-only build work for you?

Do you have CUDA installed? Which version of CUDA? Also, is cuDNN installed? Have you configured Tensorflow to use GPU (`cd tensorflow && ./configure`)?

Lastly, which OS are you building on?

**Comment by fuyiqin** [comment]
Thanks for your answer
The cpu-only build could work for me, and I tryed the caffe and caffe-ssd.
OS：ubuntu14.04
CUDA：8.0   cuDNN：5.1
I performed  (cd tensorflow && ./configure), but showed the error above.

**Comment by fuyiqin** [comment]
oh, the cpu-only build could work for me, and I try the caffe and caffe-ssd

**Comment by tspthomas** [comment]
Hi,
I'm facing the same error and my setup is Ubuntu 16.04.
Do you have any thoughts on how we can fix this?
Thanks!

**Comment by rayglover-ibm** [comment]
Forgot to ask (probably the most important question), which version of Bazel are you using?

**Comment by tspthomas** [comment]
In my case, I'm using Bazel 0.4.5.

**Comment by tspthomas** [comment]
Hi @rayglover-ibm,

Could you please say if there is any other information you need from my side? We would like to know how we could make it run with GPU :)

Thank you!

**Comment by rayglover-ibm** [comment]
Sorry for the delay, I've only just found some time to look at this. I think the fix in 35ab6e7  should be sufficient.

This is due to changes in cuda configuration in Tensorflow from a while ago.

**Comment by tspthomas** [comment]
Thank you @rayglover-ibm! It worked just fine :)
