### ISSUE TITLE
Build Issue with Bazel version 0.5.1 - no such package '@caffe_tools//'

### ISSUE THREAD

**Issue by delta9** [rayglover-ibm/serving-caffe#6]
I'm getting the following error when trying to build:

> $ bazel build -c opt @caffe//:lib
WARNING: /home/user/.cache/bazel/_bazel_user/2b47f839fb1451bdb7624c418c4327a9/external/org_tensorflow/tensorflow/workspace.bzl:63:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
ERROR: error loading package '@caffe//': Encountered error while reading extension file 'config.bzl': no such package '@caffe_tools//': No WORKSPACE file found in /home/user/.cache/bazel/_bazel_user/2b47f839fb1451bdb7624c418c4327a9/external/caffe_tools.
INFO: Elapsed time: 0.068s

Bazel version is 0.5.1.

Any help would be much appreciated.

Many thanks,

Melvin

UPDATE: It starts building with bazel version 0.4.5

**Comment by rayglover-ibm** [comment]
Thanks for reporting this. It seems the `@caffe_tools//:config.bzl` label stopped working in bazel 0.5. I'll look in to this some more once I get a moment.

**Comment by rayglover-ibm** [comment]
Bazel 0.5 needs a `WORKSPACE` file for all local repositories. fixed in 172c860
