### ISSUE TITLE
need recompile everytime when trying to debug with my caffe

### ISSUE THREAD

**Issue by wspstorm** [rayglover-ibm/serving-caffe#8]
Hi,
     when I trying to make it work with modified caffe, each time I change the code. I must bazel clean and then recompile caffe and tensorflow server to make it work.

     is there someway more efficient to do so?

**Comment by rayglover-ibm** [comment]
Good question. Really this is about how the Caffe build (CMake) is integrated in to the TensorFlow Serving build (Bazel). Bazel doesn't know how the Caffe build itself works other than it creates `lib/libcaffe.a` and some other files. You might be able to avoid rebuilding *everything* by removing this file, forcing just Caffe and dependents to be rebuilt, and not TensorFlow.

Perhaps there is a feature of Bazel that makes this easier but I don't know what it is.
