### ISSUE TITLE
Support for caffe2

### ISSUE THREAD

**Issue by akurniawan** [rayglover-ibm/serving-caffe#9]
Hi, thanks for the fork to make serving able to serve caffe model!
Is there any plan to support caffe2? Or is that should be in separate repository? I couldn't find any in google for caffe2
Thanks!

**Comment by yjhjstz** [comment]
+1

**Comment by rayglover-ibm** [comment]
I don't personally plan on supporting Caffe2.

It should be possible to support Caffe2, however, the intention of this was to make it easier for teams using Caffe to move towards TensorFlow.
